### ISSUE TITLE
[FEATURE] Parse GitHub style code blocks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#296] opened 2015-04-22 18:37 UTC
```
GitHub uses classes to identify language, so e.g.

<pre><code class="ruby">
def foo
  puts "bar"
end
</code></pre>

Is it possible to add support to it somehow? Or there is a way to configure 
Prettify to detect language from this structure?
```

Original issue reported on code.google.com by `hrgys...@gmail.com` on 13 Jul 2013 at 12:14

**Comment by amroamroamro** [comment] 2017-01-21 12:30
This is mentioned in the README file:
- https://github.com/google/code-prettify/blob/master/README.md#how-do-i-specify-the-language-of-my-code
- https://github.com/google/code-prettify/blob/master/README.md#i-cant-add-classes-to-my-code-because-it-comes-from-markdown-etc

So it supports language hints as `class="lang-ruby"` or `class="language-ruby"`.

When it's not possible to specify classes (e.g. when converting markdown to html), you can use a preceding HTML comment or XML processing instruction to set language hint

```html
<!--prettify lang=ruby-->
```

(see https://github.com/google/code-prettify/issues/250#issuecomment-273932160 for an example)

I'm closing this as duplicate of https://github.com/google/code-prettify/issues/224#issuecomment-95295214, since it seems to be asking for something similar.

**Closed by amroamroamro** 2017-01-21 12:30 UTC
Labels: auto-migrated, enhancement, question, Status-Duplicate
