### ISSUE TITLE
Tag a git(hub) release

### ISSUE THREAD

**Issue by megawac** [google/code-prettify#459] opened 2016-11-03 04:01 UTC
It would be awesome if there were git tags/releases on the repo so I could configure syncing with the jsdelivr cdn (http://www.jsdelivr.com/, https://github.com/jsdelivr/jsdelivr#auto-updating)

**Comment by amroamroamro** [comment] 2016-12-11 19:03
duplicate of #389

**Closed by amroamroamro** 2016-12-11 19:03 UTC
