### ISSUE TITLE
How to use language extensions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#332] opened 2015-04-22 18:37 UTC
```
I am manually loading prettify.js (not using auto-loader) and I added the 
contents of lang-go.js to the bottom of prettify.js. Then I have:

<pre class="prettyprint lang-go linenums"> ...

But the go code is not being highlighted properly. Am I missing something?
```

Original issue reported on code.google.com by `i...@nodesocket.com` on 25 Feb 2014 at 1:13

**Comment by amroamroamro** [comment] 2016-12-12 00:53
duplicate of of #334

**Closed by amroamroamro** 2016-12-12 00:53 UTC
Labels: auto-migrated, lang-go, question, Status-Duplicate
