### ISSUE TITLE
404 when I try to download the resources

### ISSUE THREAD

**Issue by henrywright** [google/code-prettify#481] opened 2017-03-07 16:02 UTC
The link in the [Getting Started](https://github.com/google/code-prettify/blob/master/docs/getting_started.md) page is returning a 404

https://raw.githubusercontent.com/google/code-prettify/master/distrib/prettify-small.tgz

**Comment by alex-milanov** [comment] 2017-03-07 16:52
#479

**Comment by henrywright** [comment] 2017-03-07 16:53
There seems to be a .zip available here

https://github.com/google/code-prettify/blob/master/distrib/prettify-small.zip

**Comment by amroamroamro** [comment] 2017-03-13 16:13
yep, forgot to update the docs. ZIP file is still provided.
Closing as duplicate of #479.

**Closed by amroamroamro** 2017-03-13 16:13 UTC
Labels: Status-Duplicate
